### PR TITLE
#3 Bump gnome sdk to version 40

### PR DESCRIPTION
**Pull request by Swissbite**
Reslolves #3

Build, package and install local on Ubuntu 20.10 / Pop!OS 20.10

### CODE REVIEW

**Comment by Swissbite** [comment]
There is also an updated `libgnome-games-support` available. Shall I also update this version within this PR or should I open a new issue and create a new P?

**Comment by Swissbite** [comment]
Local install and run worked, as mentioned in https://github.com/flathub/org.gnome.five-or-more/pull/4#issuecomment-822040496

**Comment by bilelmoussaoui** [comment]
> There is also an updated `libgnome-games-support` available. Shall I also update this version within this PR or should I open a new issue and create a new P?

Feel free to do that on the same PR

**Comment by bilelmoussaoui** [comment]
Thanks a lot!

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by Swissbite** [comment]
After remove the previous version:
Local install and run worked, as mentioned in https://github.com/flathub/org.gnome.five-or-more/pull/4#issuecomment-822045281

**Pull request merged**
